import cron from 'node-cron';
import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import { google } from "googleapis";
import cookieParser from "cookie-parser";
import axios from "axios";
import { GoogleGenAI, Type } from "@google/genai";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', 'https://neural-tube.vercel.app');
  res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization');
  if (req.method === 'OPTIONS') return res.sendStatus(200);
  next();
});
  const PORT = 3000;

  app.use(express.json());
  app.use(cookieParser());

  const oauth2Client = new google.auth.OAuth2(
    process.env.YOUTUBE_CLIENT_ID,
    process.env.YOUTUBE_CLIENT_SECRET,
    `${process.env.APP_URL || 'http://localhost:3000'}/api/auth/youtube/callback`
  );

  // YouTube OAuth URL
  app.get("/api/auth/youtube/url", (req, res) => {
    if (!process.env.YOUTUBE_CLIENT_ID || !process.env.YOUTUBE_CLIENT_SECRET) {
      return res.status(500).json({ 
        error: "YouTube API credentials missing", 
        details: "Please set YOUTUBE_CLIENT_ID and YOUTUBE_CLIENT_SECRET in AI Studio Secrets." 
      });
    }

    const scopes = [
      "https://www.googleapis.com/auth/youtube.upload",
      "https://www.googleapis.com/auth/youtube.readonly"
    ];

    try {
      const url = oauth2Client.generateAuthUrl({
        access_type: "offline",
        scope: scopes,
        prompt: "consent"
      });
      res.json({ url });
    } catch (error) {
      console.error("Error generating auth URL:", error);
      res.status(500).json({ error: "Failed to generate authorization URL" });
    }
  });

  // YouTube OAuth Callback
  app.get("/api/auth/youtube/callback", async (req, res) => {
    const { code } = req.query;
    try {
      const { tokens } = await oauth2Client.getToken(code as string);
      
      res.send(`
        <html>
          <body>
            <script>
              if (window.opener) {
                window.opener.postMessage({ 
                  type: 'YOUTUBE_AUTH_SUCCESS', 
                  tokens: ${JSON.stringify(tokens)} 
                }, 'https://neural-tube.vercel.app');
                window.close();
              } else {
                window.location.href = '/';
              }
            </script>
            <p>Authentication successful. This window should close automatically.</p>
          </body>
        </html>
      `);
    } catch (error) {
      console.error("Error exchanging code for tokens:", error);
      res.status(500).send("Authentication failed");
    }
  });

  // YouTube Upload API
  app.post("/api/youtube/upload", async (req, res) => {
    const { tokens, title, description, niche, videoId: vidId } = req.body;
    
    if (!tokens) {
      return res.status(401).json({ error: "YouTube not connected" });
    }

    try {
      oauth2Client.setCredentials(tokens);
      const youtube = google.youtube({ version: "v3", auth: oauth2Client });

      const videoFilePath = path.join(process.cwd(), 'public', 'assets', `final_${vidId}.mp4`);
      if (!fs.existsSync(videoFilePath)) {
        return res.status(404).json({ error: "Rendered video file not found" });
      }
      const videoStream = fs.createReadStream(videoFilePath);

      const uploadResponse = await youtube.videos.insert({
        part: ["snippet", "status"],
        requestBody: {
          snippet: {
            title: `[AI Generated] ${title}`,
            description: `${description}\n\nGenerated by NeuralTube AI Automation.`,
            tags: [niche, "AI", "Automation", "NeuralTube"],
            categoryId: "22"
          },
          status: {
            privacyStatus: "unlisted",
            selfDeclaredMadeForKids: false
          }
        },
        media: {
          body: videoStream.data
        }
      });

      const videoId = uploadResponse.data.id;
      const channelResponse = await youtube.channels.list({ part: ["snippet"], mine: true });
      const channel = channelResponse.data.items?.[0];
      
      res.json({ 
        success: true, 
        videoId: videoId,
        channelTitle: channel?.snippet?.title,
        channelId: channel?.id
      });
    } catch (error) {
      console.error("YouTube Upload Error:", error);
      res.status(500).json({ error: "Failed to upload to YouTube" });
    }
  });

  // Codebase Audit API
  app.get("/api/codebase/files", async (req, res) => {
    try {
      const fs = await import("fs/promises");
      const { glob } = await import("glob");
      
      const files = await glob("src/**/*.{ts,tsx,css}", { ignore: "node_modules/**" });
      const fileContents = await Promise.all(
        files.map(async (file) => ({
          path: file,
          content: await fs.readFile(file, "utf-8")
        }))
      );
      
      res.json(fileContents);
    } catch (error) {
      console.error("Failed to read codebase:", error);
      res.status(500).json({ error: "Failed to read codebase" });
    }
  });

 // Gemini AI Proxy API
let lastGeminiCall = 0;
const GEMINI_DELAY_MS = 3000;
const callGeminiWithRateLimit = async (genAI: any, model: string, contents: any, config: any) => {
  const now = Date.now();
  const timeSinceLast = now - lastGeminiCall;
  if (timeSinceLast < GEMINI_DELAY_MS) {
    await new Promise(resolve => setTimeout(resolve, GEMINI_DELAY_MS - timeSinceLast));
  }
  lastGeminiCall = Date.now();
  return genAI.models.generateContent({ model, contents, config });
};
};
app.post("/api/ai/generate", async (req, res) => {
  const { model, contents } = req.body;
  try {
    const { VertexAI } = await import("@google-cloud/vertexai");
    const credsJson = process.env.GOOGLE_APPLICATION_CREDENTIALS_JSON;
    const googleAuthOptions = credsJson ? { credentials: JSON.parse(credsJson) } : {};
    const vertexAI = new VertexAI({ project: "neuraltube-app", location: "us-central1", googleAuthOptions });
    const gm = vertexAI.getGenerativeModel({ model: model || "gemini-2.0-flash-001" });
    const prompt = contents.map((c: any) => c.parts.map((p: any) => p.text).join(" ")).join(" ");
    const result = await gm.generateContent(prompt);
    const text = result.response.candidates?.[0]?.content?.parts?.[0]?.text || "";
    res.json({ text });
  } catch (error) {
    console.error("Vertex AI Error:", error);
    res.status(500).json({ error: "AI Generation failed", details: error instanceof Error ? error.message : "Unknown error" });
  }
});
     

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("/{*path}", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  
cron.schedule('0 8 * * *', async () => {
  console.log('Running daily automation...');
  try {
    const trends = await scanForTrends("Technology");
    const bestTrend = trends[0];
    if (!bestTrend) return;
    console.log('Automation triggered for:', bestTrend.topic);
  } catch (error) {
    console.error('Automation failed:', error);
  }
});
app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
// cache bust Fri Apr 17 10:01:51 AM UTC 2026
